### PR TITLE
Allow `gestureRecognizerSwiped` to be overridable

### PR DESCRIPTION
**Pull request by v-ken**
I think it would be useful to allow custom behaviour for user swipes on the elongation cells.

### CODE REVIEW

**Comment by v-ken** [comment]
@Jauzee Any chance to get this merged?

**Comment by av0c0der** [comment]
Sorry for the delay. You changed access level of this method in subclass. It must be changed in supeclass `SwipableTableViewController`.

@v-ken can you please explain what is the purpose of overriding this method?

**Comment by v-ken** [comment]
@Jauzee I think it's useful for users to decide the behaviour of the swipes. E.g. I use it to collapse the cells but not to present the detailed view controller.

Should I make the changes in `SwipableTableViewController` instead?

**Comment by av0c0der** [comment]
@v-ken I think it's be better to extend [`ElongationConfig`](/ElongationPreview/Source/ElongationConfig.swift) and add `cellSwipeAction` like [these](https://github.com/Ramotion/elongation-preview/blob/master/ElongationPreview/Source/ElongationConfig.swift#L21-L36) actions.

Can't promise you that I'll do this soon, but you can try. It would be very helpful.

**Pull request closed without merging**
